### ISSUE TITLE
Sometimes RVerify.js does not hide after solving

### ISSUE THREAD

**Issue by beshoo** [zpfz/RVerify.js#5]
Dear support.
Thank you for this wonderful project.
Today while am testing RVerify.js, I have this case when I solved the RVerify correctly, but it does not hide the RVerify.js modal. and I can not close it anymore even though the close button is disabled the slider, everything is disabled.

 Please Advice.
Is there an API to call so I can assure the RVerify closed!

**Comment by zpfz** [comment]
you can use [RVerify.action()](https://rverify.pages.dev/#basic-usage) to solve. According to the different return values, handling the action when the modal closed. You can also provide a demo in [codepen.io](https://codepen.io/) to reproduce the problem you encountered~
