### ISSUE TITLE
Check without opening the modal

### ISSUE THREAD

**Issue by noum** [zpfz/RVerify.js#8]
Say the user already did rotate the image correctly and now he wants to click on the submit button.
How can we check the status of the RVerify before sending the form without reopening the modal which RVerify.action() basically does?
Something like RVerify.check() or RVerify.status() would be great.

**Comment by zpfz** [comment]
you can try to send the verification code to the server, and fetch the encrypted string (encrypted by `AES`/`DES`/... ) into `localStorage`. when the user clicks on the submit button, it will decrypt the string ( likes `crypto-js` ) to identify the status of RVerifyJS. Additional, RVerify.js  was designed that doesn't incorporate backend validation at present.
